# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties

# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.20.1
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.20.1,1.21)
# The Forge version must agree with the Minecraft version to get a valid artifact
forge_version=47.4.3
# The Forge version range can use any version of Forge as bounds or match the loader version range
forge_version_range=[47,)
# The loader version range can only use the major version of Forge/FML as bounds
loader_version_range=[47,)
# The mapping channel to use for mappings.
# The default set of supported mapping channels are ["official", "snapshot", "snapshot_nodoc", "stable", "stable_nodoc"].
# Additional mapping channels can be registered through the "channelProviders" extension in a Gradle plugin.
#
# | Channel   | Version              |                                                                                |
# |-----------|----------------------|--------------------------------------------------------------------------------|
# | official  | MCVersion            | Official field/method names from Mojang mapping files                          |
# | parchment | YYYY.MM.DD-MCVersion | Open community-sourced parameter names and javadocs layered on top of official |
#
# You must be aware of the Mojang license when using the 'official' or 'parchment' mappings.
# See more information here: https://github.com/MinecraftForge/MCPConfig/blob/master/Mojang.md
#
# Parchment is an unofficial project maintained by ParchmentMC, separate from Minecraft Forge.
# Additional setup is needed to use their mappings, see https://parchmentmc.org/docs/getting-started
mapping_channel=official
# The mapping version to query from the mapping channel.
# This must match the format required by the mapping channel.
mapping_version=1.20.1


## Mod Properties

# Millenaire_Rewrite mod的唯一标识符。必须为英文小写。必须符合正则表达式 [a-z][a-z0-9_]{1,63}
# 必须与主mod类中@Mod注解的字符串常量匹配。
mod_id=millenaire_rewrite
# mod的人类可读显示名称。
mod_name=Millenaire Rewrite
# mod的许可证。查看选项：https://choosealicense.com/。默认为All Rights Reserved。
mod_license=MIT
# mod版本。参见：https://semver.org/
mod_version=0.1.0-alpha
# mod的群组ID。仅在发布为Maven仓库的构件时重要。
# 这应该与mod源代码使用的基础包匹配。
# 参见：https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=com.jasoncian.millenaire_rewrite
# mod的作者。这是一个简单的文本字符串，用于在mod列表中显示。
mod_authors=JasonCian
# mod的描述。这是一个简单的多行文本字符串，用于在mod列表中显示。
mod_description=Millenaire mod的1.20.1现代化重制版本。